storage:
  diretorio_documentos: "./storage/documentos"
  diretorio_metadata: "./storage/metadata"
  diretorio_backups: "./storage/backups"
  diretorio_exportacoes: "./storage/exportacoes"
  diretorio_logs: "./storage/logs"

upload:
  tamanho_maximo_mb: 20

hash:
  algoritmo: "sha-256"

backup:
  formato: "zip"

logging:
  version: 1

  formatters:
    app:
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

    atividade:
      format: "%(asctime)s - %(name)s - %(levelname)s - acao=%(acao)s - documento_id=%(documento_id)s - documento=%(documento)s - resultado=%(resultado)s"

  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: app
      stream: ext://sys.stdout

    app_file:
      class: logging.FileHandler
      level: DEBUG
      formatter: app
      filename: app.log
      encoding: utf-8

    atividades_file:
      class: logging.FileHandler
      level: INFO
      formatter: atividade
      filename: atividade.log
      encoding: utf-8


  loggers:
    logger_api:
      level: DEBUG
      handlers:
        - console
        - app_file
      propagate: false

    logger_atividades:
      level: INFO
      handlers:
        - console
        - atividades_file
      propagate: false


  root:
    level: WARNING
    handlers:
      - console