from enum import Enum

class AcaoAtividade(str, Enum):
    EXPORT_DOCUMENTS = "EXPORT_DOCUMENTS"
    DOCUMENT_CREATE = "DOCUMENT_CREATE"
    DOCUMENT_UPDATE = "DOCUMENT_UPDATE"
    DOCUMENT_DELETE = "DOCUMENT_DELETE"
    DOCUMENT_UPLOAD = "DOCUMENT_UPLOAD"
    DOCUMENT_DOWNLOAD = "DOCUMENT_DOWNLOAD"
    INTEGRITY_CHECK = "INTEGRITY_CHECK"

class ResultadoAtividade(str, Enum):
    SUCCESS = "SUCCESS"
    FAILURE = "FAILURE"
    NOT_FOUND = "NOT_FOUND"
    CONFLICT = "CONFLICT"
